### ISSUE TITLE
safe shutdown sequence

### ISSUE THREAD

**Issue by pinkywafer** [cmroche/OctoPrint-HomeAssistant#20]
First, thanks for this, Love this plugin
Not an issue really... just thought you'd like to see my safe shutdown 

```yaml
ender3_safe_power_down:
    alias: Ender3 Safe Power Down
    sequence:
      - condition: state
        entity_id: binary_sensor.octoprint_printing
        state: 'off'
      - service: switch.turn_on
        entity_id: switch.octoprint_shutdown_system
      - wait_template: "{{ is_state('sensor.octoprint_print_status', 'unavailable') }}"
        timeout: '00:01:00'
      - delay:
          seconds: 10
      - service: switch.turn_off
        entity_id: switch.3d_printer_psu
```
I'm checking for the system going "Unavailable" rather than arbitrarily waiting a set period

**Comment by cmroche** [comment]
Thanks for sharing.

This is running on an RPI? And 10 seconds you find to be enough?

**Comment by pinkywafer** [comment]
I've done another edit which seems to be better...
Octoprint running on RPi 3B+ on same PSU as the printer

``` yaml
script:
  ender3_safe_power_down:
    alias: Ender3 Safe Power Down
    sequence:
      - condition: not                                     # checks that the printer is NOT printing
        conditions:                                        # I did it this way, as the binary sensor will be 
          condition: state                                 # 'unavailable' if the server has been manually
          entity_id: binary_sensor.octoprint_printing      # shutdown
          state: 'on'
      - service: switch.turn_on
        entity_id: switch.octoprint_shutdown_system        # shutdown octoprint
      - wait_template: "{{ is_state('sensor.octoprint_print_status', 'unavailable') }}"  # Waits until MQTT reports unavailable
      - delay:                                             # wait an extra 10 seconds (just to be sure!)
          seconds: 10
      - service: switch.turn_off                           # turn off psu
        entity_id: switch.3d_printer_psu
```

I've removed the timeout altogether as it's not really needed.
From my testing, the rpi is normally shut down in about 30 seconds - 1 minute. 
MQTT unavailable message usually takes around 1minute 20 seconds
The wait template "pauses" the script until the MQTT unavailable message, and should be sufficient, but I've given an extra 10 seconds "just in case!"
