### ISSUE TITLE
How to send Gcode comands

### ISSUE THREAD

**Issue by Sleeepy2** [cmroche/OctoPrint-HomeAssistant#28]
I just want to be able to send M80 and M81 for PSU control but I can't figure out how to send these.

**Comment by cmroche** [comment]
Consider this example, which calls an MQTT service to publish a command to the homing topic.

```yaml
type: entity-button
name: Home all axes
tap_action:
  action: call-service
  service: mqtt.publish
  service_data:
    topic: octoprint/virtual_p/hassControl/home
    payload: '["x", "y", "z"]'
```

The only change here is that you want to send raw gcode commands to `octoprint/virtual_p/hassControl/commands`, the `payload` field will be a string with your gcode commands, ie: `payload: "M80"`

**Comment by Sleeepy2** [comment]
Right sorry, it was late when I sent this. It's the topic that I am not sure of. Is this topic default for everyone or is the "virtual_p" part unique to the printer? I have my button set like this, it just doesn't do anything.
```
type: entity-button
tap_action:
  action: call-service
  service: mqtt.publish
  service_data:
    topic: octoprint/virtual_p/hassControl/commands
    payload: '["M80"]'
```
