### ISSUE TITLE
A few corrections for the setup instructions on this project home page

### ISSUE THREAD

**Issue by DarKOrange75** [cmroche/OctoPrint-HomeAssistant#38]
Hi,

First, there is a forgotten parenthesis in the "Safe shutdown of Raspberry Pi" section:

`- wait_template: "{{ is_state('sensor.ender_3_print_status', 'unavailable') }}"`

Second, if you want to stream the camera feed, set it up as a generic camera instead of mjpeg camera (this was not working for me), with the following I can even see the stream in Homekit!

```
camera:
  - platform: generic
    name: Octopi
    still_image_url: "http://octopi.local/webcam/?action=snapshot"
    stream_source: "http://octopi.local/webcam/?action=stream"

```
Hope it helped,

Cheers,

Laurent
