### ISSUE TITLE
Multiple Commands not working

### ISSUE THREAD

**Issue by MTrab** [cmroche/OctoPrint-HomeAssistant#83]
Trying to issue multiple commands in one publish, but nothing happens.
Isn't this supported, like the OctoPrint API states?

```
    action: call-service
    service: mqtt.publish
    service_data:
      topic: octoprint/core_a8/hassControl/commands
      payload: '["G28","G0 Z300"]'
```
