### ISSUE TITLE
Multiple Octoprint Instances

### ISSUE THREAD

**Issue by huskyte** [cmroche/OctoPrint-HomeAssistant#88]
Three Octoprint Installations are just being discovered as two. Surely they all came out of one initial configuration and were copied (recently again as to move thme to ProxMox). I changed the key in the homeassisatant discovery as well as deleted the API key for homeassistant in Octoprint.

Still no luck. 

Which are the defenitive identifiers towards home assistant? Is there anything else that needs to be deleted? And yes, I gave the hints here a thought, but there must be some residue somewhere else.

**Comment by cmroche** [comment]
It's determined by the `node_id` and `unique_id` both from the configuration. Make sure you update both of these values in the config.yaml, and delete the devices in the **MQTT** integration so they are reloaded when OctoPrint is restarted.

```
  homeassistant:
    _config_version: 2
    node_id: 029b12add632423ba24321a67cff34cb
    unique_id: 029b12ad-d632-423b-a243-21a67cff34cb
```
